noun = input("Enter a noun")
print("The Time I Flew A Plan")
noun1 = input("Enter a noun")
print("Bob sat down in the time was now he picked up his" + noun )
verb = input("Enter a verb")
print("Bob began to cry because the was" + noun1 )
print("When Bob was done crying the kid in front of him " + verb)
verb2 = input("Enter a verb") 
print("Bob was now angry and got up to " + verb2)
noun2 = input ("Enter a noun")
print(noun2 + "ran and laughed at Bob") 
verb3 = input ("Enter a verb") 
print("Trump came onto the airplane and began to" + verb3 )
verb4 = input ("Enter a verb")
print("Bob stood up and ran to Trump and" + verb4)
adjictive = input ("Enter an adjective")
print("Bob and Trump began to look jump around the plan everyone else thought this was crazy and they looked" + adictive)
verb6 = input ("Enter a verb")
print('suddenly everyone began to scream as they realised Trump was a flight attendent on the plan')
print( "worried nervous and began to" + verb6 )
